### ISSUE TITLE
Plans to release the code?

### ISSUE THREAD

**Issue by jianwang-mpi** [korrawe/Diffusion-Noise-Optimization#1]
Hello, 

Thanks a lot for your great work! I want to ask if you have any plans to release the code. 

Looking forward to your response,

Jian Wang

**Comment by korrawe** [comment]
Hi, we are planning to release the code around the end of Jan or early Feb, subject to other factors

**Comment by ktxu1224** [comment]
Hello, Thanks a lot for such a great work! I wonder when you will release the code? @korrawe @phizaz
