### ISSUE TITLE
What is the form of ODE in MDM?

### ISSUE THREAD

**Issue by ChambinLee** [korrawe/Diffusion-Noise-Optimization#2]
Hello,

Thanks a lot for your great work! 

As far as I know, you have used MDM's network as the BASE model in the EXPERIMENTS part of your paper, and the METHOD part utilizes its ODE form to implement your requirements. I would like to know how you guys got this ODE form. And what is its SDE form?

I appreciate any help you can provide.

**Comment by korrawe** [comment]
We use DDIM for the ODE solver.

I am how the SDE is related here.
Best,
