### ISSUE TITLE
source-target frame-editing

### ISSUE THREAD

**Issue by tucker666** [korrawe/Diffusion-Noise-Optimization#5]
Thanks a lot for your great work! I'm interesting in source-target frame-editing part

Looking forward to the  code.

**Comment by korrawe** [comment]
You can check the code for pose editing [here](https://github.com/korrawe/Diffusion-Noise-Optimization/blob/2aa7db55e2e71de87a12dc3198bb3552e730c2bb/sample/dno_helper.py#L92)

Best,
