### ISSUE TITLE
GUI for joint editing

### ISSUE THREAD

**Issue by miraymen** [korrawe/Diffusion-Noise-Optimization#6]
Hi

Thanks for releasing the code. In the readme you talk about a GUI for creating test motion sequences, a variable USE_GUI. I can't find this code anywhere. Will it please be possible for you to release this code as well.

**Comment by korrawe** [comment]
The USE_GUI part refers to this [line](https://github.com/korrawe/Diffusion-Noise-Optimization/blob/2aa7db55e2e71de87a12dc3198bb3552e730c2bb/sample/dno_helper.py#L53) in [sample/dno_helper.py](https://github.com/korrawe/Diffusion-Noise-Optimization/tree/2aa7db55e2e71de87a12dc3198bb3552e730c2bb/sample/dno_helper.py). Though, these are just parts of what I used for testing trajectory edit so they are very primitive implementation with Pyplot. 

You can use the scroll bar to select the frame, click where you want the body to be on that frame, and then click add. Then you click done.
